# Generated by Django 5.2.2 on 2025-06-15 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='author',
            new_name='owner',
        ),
    ]
